### ISSUE TITLE
How to use.

### ISSUE THREAD

**Issue by ghost** [Sade66/CSP-1.4.7-Project#2]
Hello, I'm doing something like this for my school, I was taking a look at your code and love it. I had a question, upon running how does it / where does it grab the images. I see it's in the working directory. I have an image in that directory but upon running it does nothing.
Thanks for the help!

**Comment by Sade66** [comment]
Thanks! It’s been a while, but make sure you’re using the file labeled FINAL. Then, add a folder labeled images in the same directory as the python file, and put your images in there.

**Comment by ghost** [comment]
Hello @Sade66 ,
I tried opening FINAL, making a directory called Images and placing some images inside the directory. Upon running nothing happens. Do you know why?

**Comment by Sade66** [comment]
I’ll have to take a look at it and remember how it grabs the images.
